version: "3.1"

services:
  datastore:
    image: soon/datastore-emulator
    command: [ "--consistency=1.0" ]
    environment:
      - DATASTORE_PROJECT_ID=tilt-demo
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - 10080:8081

  datastore-ui:
    image: skarpdev/google-datastore-ui:1.0.0
    environment:
      DSUI_PROJECT_ID: tilt-demo
      DSUI_PORT: 8282
      DSUI_DATASTORE_ENDPOINT: datastore:8081
    ports:
      - 10082:8282
    depends_on:
      - datastore
    links:
      - datastore
